name: Terraform Apply
on:
  pull_request:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        sheell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform apply
        run: |
          terraform init
          terraform apply -auto-approve